conf db

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -1,6 +1,11 @@
 #!/bin/sh
 
 cp  -R $SNAP/etc $SNAP_DATA/
+DIR="$SNAP/var/www/onlyoffice/documentserver"
+LOG_DIR="$SNAP_DATA/var/log/onlyoffice/documentserver"
+APP_DIR="$SNAP/var/lib/onlyoffice/documentserver"
+CONF_DIR="$SNAP_DATA/etc/onlyoffice/documentserver"
+
 DEFAULT_HTTP_PORT="80"
 DEFAULT_DB_HOST="localhost"
 DEFAULT_DB_PORT="5432"
@@ -8,6 +13,36 @@ DEFAULT_DB_NAME="onlyoffice"
 DEFAULT_DB_USER="onlyoffice"
 DEFAULT_DB_PWD="onlyoffice"
 
+install_db(){
+        CONNECTION_PARAMS="-h$DEFAULT_DB_HOST -U$DEFAULT_DB_USER -w"
+        if [ -n "$DEFAULT_DB_PWD" ]; then
+                export PGPASSWORD=$DEFAULT_DB_PWD
+        fi
+
+        PSQL="$SNAP/usr/bin/psql -h 127.0.0.1 -d postgres -q $CONNECTION_PARAMS"
+        CREATEDB="$SNAP/usr/bin/createdb $CONNECTION_PARAMS"
+
+	# test postgresql connection
+	set +e
+        $PSQL -c ";" &>/dev/null
+        ERRCODE=$?
+        if [ $ERRCODE -ne 0 ]; then
+                service postgresql start &>/dev/null
+                $PSQL -c ";" &>/dev/null || { echo "ERROR: can't connect to postgressql database"; exit 1; }
+        fi
+	set -e
+
+        if ! $PSQL -lt | cut -d\| -f 1 | grep -qw $DEFAULT_DB_NAME; then
+                $CREATEDB $DEFAULT_DB_NAME >/dev/null 2>&1
+        fi
+
+        if [ ! "$CLUSTER_MODE" = true ]; then
+                $PSQL -d "$DEFAULT_DB_NAME" -f "$DIR/server/schema/postgresql/removetbl.sql" >/dev/null 2>&1
+        fi
+        $PSQL -d "$DEFAULT_DB_NAME" -f "$DIR/server/schema/postgresql/createdb.sql" >/dev/null 2>&1
+}
+
+install_db
 
 nginx_onlyoffice_http_port()
 {
